# Dockerfile-backend

# Usar una imagen base de Python
FROM python:3.12

# Crear y establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo de requisitos
COPY backend/requirements.txt ./

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código fuente
COPY backend/app/ ./app/

# Exponer el puerto en el que la aplicación estará escuchando
EXPOSE 8000

# Comando por defecto para iniciar la aplicación
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
